<?php

use Illuminate\Database\Seeder;

class NUSModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $modules = [
            'Computer Science',
            'Information Systems',
            'Computer Engineering',
            'Business Analytics',
            'Information Security',
            'Algorithms & Theory',
            'Artificial Intelligence',
            'Computer Graphics and Games',
            'Computer Security',
            'Database Systems',
            'Multimedia Information Retrieval',
            'Networking and Distributed Systems',
            'Parallel Computing',
            'Programming Languages',
            'Software Engineering',
            'Interactive Media',
            'Visual Computing',
            'CS1010 Programming Methodology',
            'CS1020 Data Structures and Algorithms I',
            'CS2010 Data Structures and Algorithms II',
            'CS1231 Discrete Structures',
            'CS2100 Computer Organisation',
            'CS2103T Software Engineering',
            'CS2105 Introduction to Computer Networks',
            'CS2106 Introduction to Operating Systems',
            'CS3230 Design and Analysis of Algorithms',
            'CS3201 Software Engineering Project',
            'CS3202 Software Engineering Project II',
            'CS3216 Software Product Engineering for Digital Markets',
            'CS3217 Software Engineering on Modern Application Platforms',
            'CS3281 Thematic Systems Project I',
            'CS3282 Thematic Systems Project II',
            'CS3283 Media Technology Project I',
            'CS3284 Media Technology Project II',
            'IS1103/FC/X Computing and Society',
            'CS2101 Effective Communication for Computing Professionals',
            'ES2660 Communicating in the Information Age',
            'MA1301/FC/X Introductory Mathematics',
            'MA1521 Calculus for Computing',
            'MA1101R Linear Algebra I',
            'ST2334 Probability and Statistics',
            'ST2131 Probability',
            'ST2132 Mathematical Statistics',
            'PC1221/FC/X Fundamental of Physics I',
            'PC1222/X Fundamentals of Physics II',
            'CS1101S Programming Methodology',
            'CS2020 Data Structures and Algorithms Accelerated',
            'CM1121 ORGANIC CHEMISTRY 1',
            'CM1131 PHYSICAL CHEMISTRY 1',
            'CM1417 FUNDAMENTALS OF CHEMISTRY',
            'LSM1301 GENERAL BIOLOGY',
            'LSM1302 GENES AND SOCIETY',
            'PC1141 PHYSICS I',
            'PC1142 PHYSICS II',
            'PC1143 PHYSICS III',
            'PC1144 PHYSICS IV',
            'PC1221 FUNDAMENTALS OF PHYSICS I ',
            'PC1222 FUNDAMENTALS OF PHYSICS II PC1432 PHYSICS IIE',
            'MA2213 NUMERICAL ANALYSIS I',
            'MA2214 COMBINATORICS AND GRAPHS I',
            'CM1101 PRINCIPLES OF MODERN CHEMISTRY ',
            'CM1111 INORGANIC CHEMISTRY 1',
            'CM1161 PRINCIPLESOF CHEMICAL PROCESS I ',
            'CM1191 EXPERIMENTS IN CHEMISTRY 1 ',
            'CM1401 CHEMISTRY FOR LIFE SCIENCES',
            'CM1402 GENERAL CHEMISTRY',
            'CM1501 ORGANIC CHEMISTRY FOR ENGINEERS',
            'CM1502 GENERAL AND PHYSICAL CHEMISTRY FOR ENGINEERS ',
            'LSM1303 ANIMAL BEHAVIOUR',
            'PC1421 PHYSICS FOR LIFE SCIENCES',
            'PC1431 PHYSICS IE',
            'PC1433 MECHANICS AND WAVES',
            'MA1104 MULTIVARIABLE CALCULUS',
            'MA2101 LINEAR ALGEBRA II',
            'MA2108 MATHEMATICAL ANALYSIS I',
            'MA2501 DIFFERENTIAL EQUATIONS AND SYSTEMS',
            'ST2132 MATHEMATICAL STATISTICS',
            'ST2137 COMPUTER AIDED DATA ANALYSIS',
            'CS3230 Design and Analysis of Algorithms (CFM)',
            'CS3236 Introduction to Information Theory',
            'CS4231 Parallel and Distributed Algorithms',
            'CS4232 Theory of Computation',
            'CS4234 Optimisation Algorithms',
            'CS3233 Competitive Programming',
            'CS5230 Computational Complexity',
            'CS5234 Combinatorial and Graph Algorithms',
            'CS5237 Computational Geometry and Applications',
            'CS5238 Advanced Combinatorial Methods in Bioinformatics',
            'CS3243 Introduction to Artificial Intelligence',
            'CS3244 Machine Learning',
            'CS4244 Knowledge-Based Systems',
            'CS4246 AI Planning and Decision Making',
            'CS4216 Constraint Logic Programming',
            'CS4220 Knowledge Discovery Methods in Bioinformatics',
            'CS4248 Natural Language Processing',
            'CS5209 Foundation in Logic & AI',
            'CS5215 Constrained Programming',
            'CS5228 Knowledge Discovery and Data Mining',
            'CS5247 Motion Planning and Applications',
            'CS5340 Uncertainty Modelling in AI',
            'CS3241 Computer Graphics',
            'CS3242 3D Modelling and Animation',
            'CS3247 Game Development',
            'CS4247 Graphics Rendering Techniques',
            'CS4350 Game Development Project',
            'CS3218 Multimodal Processing in Mobile Platforms',
            'CS3240 Interaction Design',
            'CS3249 User Interface Development',
            'CS3343 Digital Media Production',
            'CS4243 Computer Vision and Pattern Recognition',
            'CS4249 Phenomena and Theories of HCI',
            'CS4340 Digital Special Effects',
            'CS4344 Network and Mobile Gaming',
            'CS4345 General-Purpose Computation on GPU',
            'CS5240 Theoretical Foundation of Multimedia',
            'CS2107 Introduction to Information Security',
            'CS3235 Computer Security',
            'CS4236 Cryptography Theory and Practice',
            'CS4238 Computer Security Practices',
            'CS3221 Operating Systems Design and Pragmatics',
            'CS4239 Software Security',
            'CS5231 Systems Security',
            'CS5321 Network Security',
            'CS5322 Database Security',
            'CS5331 Web Security',
            'IFS4101 Legal Aspects of Information Security',
            'IS3230 Principles of Information Security',
            'IS4231 Information Security Management',
            'IS4232 Topics in Information Security',
            'CS2102 Database Systems',
            'CS3223 Database Systems Implementation',
            'CS4221 Database Applications Design and Tuning',
            'CS4224 Distributed Databases',
            'CS4225 Massive Data Processing Techniques in Data Science',
            'CS5226 Database Tuning',
            'CS2108 Introduction to Media Computing&',
            'CS3245 Information Retrieval',
            'CS4242 Social Media Computing',
            'CS4347 Sound and Music Computing',
            'CS5246 Text Processing on the Web',
            'CS5241 Speech Processing',
            'CS6242 Digital Libraries',
            'CS5342 Multimedia Computing and Applications',
            'CS3103 Computer Networks Practice',
            'CS4222 Wireless Computing',
            'CS4226 Internet Architecture',
            'CS4274 Mobile and Multimedia Networking',
            'CS4344 Networked and Mobile Gaming',
            'CS5223 Distributed Systems',
            'CS5229 Advanced Computer Networks',
            'CS5248 Systems Support for Continuous Media',
            'CS3210 Parallel Computing',
            'CS3211 Parallel and Concurrent Programming',
            'CS4223 Multi-core Architecture',
            'CS4237 Systems Modelling and Simulation',
            'CS4271 Critical Systems and Their Verification',
            'CS5207 Foundation in Operating Systems',
            'CS5222 Advanced Computer Architectures',
            'CS5239 Computer System Performance Analysis',
            'CS2104 Programming Language Concepts',
            'CS4215 Programming Language Implementation',
            'CS4212 Compiler Design',
            'CS3234 Logic and Formal Systems',
            'CS5205 Foundation in Programming Languages',
            'CS5232 Formal Specification & Design Techniques',
            'CS5214 Design of Optimising Compilers',
            'CS5218 Principles of Program Analysis',
            'CS2103 Software Engineering',
            'CS3213 Software Systems Design',
            'CS3219 Software Engineering Principles and Patterns',
            'CS4211 Formal Methods for Software Engineering',
            'CS4218 Software Testing',
            'CS3216 Software Development on Evolving Platforms',
            'CS3226 Web Programming and Applications',
            'CS3882 Breakthrough Ideas for Digital Markets',
            'CS4217 Software Development Technologies',
            'CS5219 Automatic Software Validation',
            'CS5272 Embedded Software Design',
            'IS2102 Requirements Analysis and Design',
            'IS2104 Software Team Dynamics',
            'CS3242 3D Modeling and Animation',
            'CS6243 Computational Photography',
            'CS1010J Programming Methodology',
            'IS1103/FC Computing and Society',
            'IS1105 Strategic IT Applications',
            'IS2101 Business and Technical Communication',
            'IS2103 Enterprise Systems Development Concepts',
            'IS3101 Management of Information Systems',
            'IS3102 Enterprise Systems Development Project',
            'IS4100 IT Project Management',
            'ACC1002X Financial Accounting',
            'MA1301 Introductory Mathematics',
            'MA1312 Calculus with Applications',
            'CP4101 B.Comp. Dissertation',
            'CS2106 Introduction to Operating Systems ',
            'CS3235 Introduction to Computer Security',
            'IS3220 Service Science ',
            'IS3221 Enterprise Resource Planning Systems',
            'IS3222 IT and Customer Relationship Management ',
            'IS3223 IT and Supply Chain Management ',
            'IS3240 Economics of E-Business',
            'IS3241 Enterprise Social Systems',
            'IS3242 Software Quality Management',
            'IS3243 Technology Strategy and Management',
            'IS3250 Health Informatics',
            'IS3251 Principles of Technology Entrepreneurship',
            'IS3260 Gamification for Organisations and Individuals',
            'IS3261 Mobile Apps Development',
            'CS4880 Digital Entrepreneurship',
            'IS4202 Global Virtual Project',
            'IS4203 IT Adoption and Change Management',
            'IS4204 IT Governance',
            'IS4224 Service Systems ',
            'IS4225 Strategic IS Planning ',
            'IS4226 IT Outsourcing and Offshoring Management ',
            'IS4227 Enterprise Service-Oriented Architecture ',
            'IS4228 Information Technologies in Financial Services',
            'IS4232 Topics in Information Security Management',
            'IS4233 Legal Aspects of Information Technology',
            'IS4234 Control and Audit of Information Systems',
            'IS4240 Business Intelligence Systems',
            'IS4241 Social Media Network Analysis',
            'IS4243 Information Systems Consulting',
            'IS4250 Healthcare Analytics',
            'IS3150 Digital and New Media Marketing',
            'IS4150 Mobile and Ubiquitous Commerce',
            'IS4260 E-Commerce Business Models',
            'IS3222 IT and Customer Relationship Management',
            'IS3261 Mobile Apps Development for Enterprise',
            'IS4225 Strategic IS Planning',
            'IS4010 Industry Internship Programme',
            'BT1101 Introduction to Business Analytics',
            'CS1010S Programming Methodology',
            'EC1301 Principles of Economics',
            'IS1103 Computing and Society',
            'MA1311 Matrix Algebra and Applications',
            'MA1101R Linear Algebra I2',
            'MA1102R Calculus2',
            'MKT1003X Marketing',
            'BT2101 IT and Decision Making',
            'BT2102 Data Management and Visualisation',
            'IE2110 Operations Research I3',
            'DSC3214 Introduction To Optimisation',
            'IS2101 Business and Technical Communication4',
            'BT3101 Business Analytics Capstone Project',
            'BT3102 Computational Methods for Business Analytics',
            'BT3103 Application Systems Development for Business Analytics',
            'ST3131 Regression Analysis',
            'BT4101 B.Sc. Dissertation',
            'DSC3224 Dynamic Pricing and Revenue Management',
            'IE3120 Manufacturing Logistics',
            'BT4211 Data-Driven Marketing',
            'BT4212 Search Engine Optimization and Analytics',
            'DSC4213 Analytical Tools for Consulting',
            'MKT4415C Seminars in Marketing: Applied Market Research',
            'DSC3216 Forecasting for Managerial Decisions',
            'BSP4513 Econometrics: Theory & Practical Business Application',
            'BT4221 Big Data Techniques and Technologies',
            'BT4222 Mining Web Data for Business Insights',
            'IE4210 Operations Research II',
            'ST4240 Data Mining',
            'ST4245 Statistical Methods for Finance',

        ];

        foreach ($modules as $module) {
            \App\Topic::create([
                'name' => $module,
            ], 1);
        }
    }
}
