<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class Bookmark extends Model
{
    /**
     * Define fillable fields
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'is_public',
    ];

    /**
     * Override create method for creating necessary associate model
     *
     * @param array $attributes
     * @return static
     */
    public static function create(array $attributes = []) {
        $bookmark = parent::create($attributes); // TODO: Change the autogenerated stub
        // bookmark hit
        Hit::create([
            'owner_type' => 'App\Bookmark',
            'owner_id' => $bookmark->id
        ]);
        return $bookmark;
    }

    /**
     * A bookmark blongs to a user
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function owner() {
        return $this->belongsTo('App\User', 'user_id');
    }

    /**
     * A bookmark has many questions
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function questions() {
        return $this->belongsToMany('App\Question', 'bookmark_question')->withTimestamps();
    }

    /**
     * A bookmark has many answers
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function answers() {
        return $this->belongsToMany('App\Answer', 'bookmark_answer')->withTimestamps();
    }

    /**
     * A bookmark is subscribed by many users
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function subscribers() {
        return $this->belongsToMany('App\Subscribe', 'subscribe_bookmark')->withTimestamps();
    }

    /**
     * A bookmark may have comment
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function replies() {
        return $this->morphMany('App\Reply', 'for_item');
    }

    /**
     * A bookmark has a hit object
     */
    public function getHitAttribute() {
        return Hit::whereOwnerType('App\Bookmark')->whereOwnerId($this->id)->first();
    }

    /**
     * Check if a item is in the bookmark
     *
     * @param $bookmark_id
     * @param $item_id
     * @param $item_type
     * @return bool
     */
    public static function isIn($bookmark_id, $item_id, $item_type) {
        if ($item_type == 'question') {
            return DB::table('bookmark_question')
                ->whereBookmarkId($bookmark_id)
                ->whereQuestionId($item_id)
                ->count() > 0;
        } else if ($item_type == 'answer') {
            return DB::table('bookmark_answer')
                ->whereBookmarkId($bookmark_id)
                ->whereAnswerId($item_id)
                ->count() > 0;
        }
    }

    /**
     * Get all public bookmark
     *
     * @param $query
     * @return mixed
     */
    public function scopePublicItem($query) {
        return $query->where('is_public', true);
    }
}
