<?php

namespace App;

use DB;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    /**
     * Define fillable field in the model
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'avatar_img_id'
    ];


    /**
     * Override create method for creating necessary associate model
     *
     * @param array $attributes
     * @return static
     */
    public static function create(array $attributes = []) {
        $topic = parent::create($attributes); // TODO: Change the autogenerated stub
        // bookmark hit
        Hit::create([
            'owner_type' => 'App\Topic',
            'owner_id' => $topic->id
        ]);
        return $topic;
    }

    /**
     * A topic will have many question
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function questions() {
        return $this->belongsToMany('App\Question');
    }

    /**
     * A topic page has a hit
     */
    public function getHitAttribute() {
        return Hit::whereOwnerType('App\Topic')->whereOwnerId($this->id)->first();
    }

    /**
     * Get recommend questions
     *
     * @return mixed
     */
    public function getRecommendQuestionsAttribute() {
        $questions = $this->questions->sortByDesc(function($question) {
            $timeDiff = Carbon::parse($question->created_at)->diffInDays(Carbon::now());
            $timeDiff = (30 - $timeDiff) > 0 ? 30 - $timeDiff : 0;
            $numSubscriber = $question->subscribers()->count();
            $numHit = $question->hit->month;
            return $numHit * 7 + $numSubscriber * 5 + $timeDiff;
        });

        return $questions;
    }

    /**
     * Get all questions without answers
     *
     * @return mixed
     */
    public function getWaitAnswerQuestionsAttribute() {
        $questions = $this->questions->filter(function($question) {
            return $question->answers()->count() == 0;
        });
        $questions = $questions->sortBy(function($question) {
            $numHit = $question->hit->month;
            $timeDiff = Carbon::parse($question->created_at)->diffInDays(Carbon::now());
            $timeDiff = (30 - $timeDiff) > 0 ? 30 - $timeDiff : 0;
            $numSubscriber = $question->subscribers()->count();
            return $numHit * 5 + $timeDiff * 2 + $numSubscriber * 4;
        });
        return $questions;
    }

    public function getHighlightQuestionsAttribute() {
        $questions = $this->questions->sortByDesc(function($question) {
            $timeDiff = Carbon::parse($question->created_at)->diffInDays(Carbon::now());
            $timeDiff = (30 - $timeDiff) > 0 ? 30 - $timeDiff : 0;
            $numSubscriber = $question->subscribers()->count();
            $numHit = $question->hit->month;
            return $numHit * 7 + $numSubscriber * 5 + $timeDiff * 3;
        });
        return $questions;
    }

    /**
     * Get hot topics
     */
    public static function getHotTopics() {
        return Topic::all()->sortByDesc(function($topic) {
            $numSubscriber = $topic->subscribers()->count();
            $numHit = $topic->hit->total;
            return $numSubscriber * 2 + $numHit * 3;
        });
    }


    /**
     * define query scope. similar match $name
     *
     * @param $query
     * @param $name
     * @return mixed
     */
    public function scopeSimilarMatch($query, $name) {
        return $query->where('name', 'REGEXP', '[' . $name . ']');
    }

    /**
     * Defined eloquent relationship : A topic can be the specialization of many students
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function specialists() {
        return $this->belongsToMany('App\User', 'user_specialization', 'topic_id', 'user_id');
    }
    

    /**
     * A topic has it parent topics
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent_topics() {
        return $this->belongsToMany('App\Topic', 'topic_subtopic', 'subtopic_id', 'parent_topic_id');
    }

    /**
     * A topic has many child topics
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function subtopics() {
        return $this->belongsToMany('App\Topic', 'topic_subtopic', 'parent_topic_id', 'subtopic_id');
    }

    /**
     * A topic is subscribed by many users' subscribe
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function subscribers() {
        return $this->belongsToMany('App\Subscribe');
    }

    /**
     * define query scope. like match $name
     *
     * @param $query
     * @param $name
     * @return mixed
     */
    public function scopeNoneSimilarMatch($query, $name) {
        return $query->where('name', 'LIKE', '%' . $name . '%');
    }

    /**
     * get top parent(topic without parent topic, root topic)
     *
     * @param $query
     * @return mixed
     */
    public function scopeTopParentTopics($query) {
        return $query->whereNotExists(function ($query) {
            $query->select(DB::raw(1))
                ->from('topic_subtopic')
                ->whereRaw('topic_subtopic.subtopic_id = topics.id');
        });
    }

}
